[package]
name = "midnight-ledger-static"
version = "9.0.0"
edition = "2024"
license.workspace = true
repository.workspace = true
description = "Version identifier of static files included in Midnight's ledger."

[dependencies]
quote = "1"
proc-macro2 = "1"

[lib]
proc-macro = true
